services:

  pluralsync-entrypoint:
    container_name: pluralsync-entrypoint
    image: nginx:1-alpine
    volumes:
      - ./template.nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./${FRONTEND_DIST}:/usr/share/nginx/html
    env_file:
      - ./${PLURALSYNC_STAGE}.env
    network_mode: host
    # ports:
    #   - ${NGINX_PORT}:${NGINX_PORT}

  pluralsync-api:
    container_name: pluralsync-api
    build:
      dockerfile: docker/rust-binary.Dockerfile
      context: ..
      args:
        PATH_TO_EXEC: ${PATH_TO_PLURALSYNC_API_EXEC}
    env_file:
      - ./${PLURALSYNC_STAGE}.env
    environment:
      DISCORD_STATUS_MESSAGE_UPDATER_AVAILABLE: "${DISCORD_STATUS_MESSAGE_UPDATER_AVAILABLE-false}"
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: 8000
    network_mode: host
    # ports:
    #   - 8000:8000

  pluralsync-db:
    # NOTE: db-migrations need to be run explicitly after startup. search for `sqlx migrate` or `sqlx::migrate!`
    image: postgres:17-alpine
    container_name: pluralsync-db
    env_file:
      - ./${PLURALSYNC_STAGE}.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pluralsync
    volumes:
      - pluralsync-data:/var/lib/postgresql/data
    restart: "on-failure:2"
    network_mode: host
    # ports:
    #   - 5432:5432


  pluralsync-global-manager:
    container_name: pluralsync-global-manager
    build:
      dockerfile: docker/rust-binary.Dockerfile
      context: ..
      args:
        PATH_TO_EXEC: ${PATH_TO_PLURALSYNC_GLOBAL_MANAGER_EXEC}
    env_file:
      - ./${PLURALSYNC_STAGE}.env
    network_mode: host

volumes:
  pluralsync-data:
    name: pluralsync-data
